name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "npm ci"
    - run: echo "npm install"
    - name: Run Lint
      run: echo "npm run lint"
    - name: Run Type Checking
      run: echo "npm run type-check"
    - name: Run Unit Tests with Jest
      run: echo "npm test"
    - name: Run Integration Tests
      run: echo "npm run test:integration"
    - name: Build
      run: echo "npm run build"
